jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Build and deploy
        run: |
          # Use the API_KEY environment variable in your commands here
          echo $API_KEY
