name: Secret Workflow

on:
  push:
    branches:
      - main


jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use API Key
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo $API_KEY
          # Use the API key in your code or perform other actions
