name: Database

on:
  push:
    branches:
      - main

jobs:
  create-database:
    runs-on: self-hosted

    steps:
      - name: Set up MySQL
        uses: actions/checkout@v2

      - name: Create Database
        run: |
          "C:\Program Files\MySQL\MySQL Server\bin\mysql.exe" -h localhost -P 3306 -u root -12345 -e "CREATE DATABASE pet-store-project;"


      - name: Import SQL File
        run: |
          "C:\Program Files\MySQL\MySQL Server\bin\mysql.exe" -h localhost -P 3306 -u root -12345 pet-store-project < C:/laragon/www/studio4-chatbot-project/pet-food-store/11.sql
