name: Database

on:
  push:
    branches:
      - main

jobs:
  create-database:
    runs-on: self-hosted

    steps:
      - name: Set up MySQL
        uses: actions/checkout@v2

      - name: Create Database
        run: |
          $env:MYSQL_HOME = "C:\laragon\bin\mysql\mysql-8.0.30-winx64\bin"
          $env:MYSQL_HOST = "localhost"
          $env:MYSQL_PORT = "3306"
          $env:MYSQL_USER = "root"
          $env:MYSQL_PASSWORD = "12345"
          $databaseName = "pet_store_project"
          cmd /c "$env:MYSQL_HOME\mysql.exe" -h $env:MYSQL_HOST -P $env:MYSQL_PORT -u $env:MYSQL_USER -p"$env:MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS \`$databaseName\`;"
