name: Chatbot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        env:
          API_KEY: ${{ secrets.API_KEY }} # Set the API_KEY secret as an environment variable

      - name: Install dependencies (if required)
        run: composer install --no-dev

      - name: Run Chatbot PHP script
        run: php chatbot.php
