name: test

on:
  push:
    branches:
      - main

 

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: secret_key
        run: setx API_KEY ${{ secrets.API_KEY }}
